name: Generate Wakatime Chart

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update Wakatime Chart
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        python gen_wakatime_chart.py
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "liu.siyao@qq.com"
        git config --global user.name "ssine-bot"
        git pull
        git add -A
        git commit -m "update chart" || exit 0
        git push